version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: '${DB_USERNAME}'
      # You can use whatever password you like
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3000:3306'
    expose:
      # Opens port 3306 on the container
      - '3000'
      - "3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  web:
    build: .
    ports:
      - "8000:8000"  # Map port 8080 on your host to port 80 in the container
    expose:
      # Opens port 3306 on the container
      - '8000'
    volumes:
      - ./:/var/www/html  # Mount your application files for live updates
    depends_on:
      - db
    command: '/bin/bash -c "php artisan migrate --seed"'
    entrypoint: '/bin/bash -c "php artisan serve --host=${APP_URL} --port=8000"'
# Names our volume
volumes:
  my-db:
